import "@fontsource/inter/variable.css";
import "@fontsource/dm-mono/latin.css";
import "@fontsource/dm-sans/latin.css";

import "./globals.css";

export const metadata = {
  title: "Schemapify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
