import "@fontsource-variable/inter";
import "@fontsource/dm-mono/latin.css";
import "@fontsource-variable/dm-sans";

import "./globals.css";

export const metadata = {
  title: "Schemapify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
